spring:
  # DB 접속 정보
  datasource:
    url: jdbc:mysql://localhost:3306/devdatabase?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari.auto-commit: false # set autocommit 호출 제거

  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties.hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true
    open-in-view: false

  sql:
    init:
      mode: always  # data.sql 실행
  data:
    web:
      pageable:
        max-page-size: 20 # Pageable 최대 size 설정

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: never

